name: deploy

on:
  push:
    branches:
      - master

jobs:
  push-to-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Set SSH Environment
        env:
          DOCS_DEPLOY_KEY: ${{ secrets.VUE_DEMO_TOKEN }}
        run: |
          mkdir -p ~/.ssh/
          echo "$VUE_DEMO_TOKEN" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com > ~/.ssh/known_hosts
          chmod 700 ~/.ssh && chmod 600 ~/.ssh/*
          git config --global user.email "wkingluoye@163.com"
          git config --global user.name "wkingluoye"

      - name: Build
        env:
          NODE_OPTIONS: '--max_old_space_size=4096'
        run: |
          yarn install --frozen-lockfile
          yarn build
          cp dist/index.html dist/404.html

      - name: Delete gh-pages branch
        run: |
          git push origin --delete gh-pages

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.9.0
        with:
          deploy_key: ${{ secrets.VUE_DEMO_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./dist
          CNAME: vben.vvbin.cn